const mongoose = require('mongoose');
const dotenv = require('dotenv');
const ProviderOperator = require('../models/ProviderOperator');
const connectDB = require('../config/db');

dotenv.config();

const operators = [
  { name: 'Airtel', code: 'A', serviceType: 'Mobile' },
  { name: 'Vodafone', code: 'V', serviceType: 'Mobile' },
  { name: 'BSNL - TOPUP', code: 'BT', serviceType: 'Mobile' },
  { name: 'RELIANCE - JIO', code: 'RC', serviceType: 'Mobile' },
  { name: 'Idea', code: 'I', serviceType: 'Mobile' },
  { name: 'BSNL - STV', code: 'BR', serviceType: 'Mobile' },
  { name: 'Airtel Digital DTH TV', code: 'ATV', serviceType: 'DTH' },
  { name: 'SUNDIRECT DTH TV', code: 'STV', serviceType: 'DTH' },
  { name: 'TATASKY DTH TV', code: 'TTV', serviceType: 'DTH' },
  { name: 'VIDEOCON DTH TV', code: 'VTV', serviceType: 'DTH' },
  { name: 'DISH TV', code: 'DTV', serviceType: 'DTH' },
  { name: 'Airtel Postpaid', code: 'PAT', serviceType: 'PostPaid' },
  { name: 'Idea Postpaid', code: 'IP', serviceType: 'PostPaid' },
  { name: 'Vodafone Postpaid', code: 'VP', serviceType: 'PostPaid' },
  { name: 'Tata Docomo Postpaid', code: 'DP', serviceType: 'PostPaid' },
  { name: 'BSNL Postpaid', code: 'BP', serviceType: 'PostPaid' },
  { name: 'Bsnl Landline', code: 'LBS', serviceType: 'PostPaid' },
  { name: 'MTNL Delhi Landline', code: 'LMT', serviceType: 'PostPaid' },
  { name: 'Airtel Landline', code: 'LAT', serviceType: 'PostPaid' },
  { name: 'JIO POSTPAID', code: 'JPP', serviceType: 'PostPaid' },
  { name: 'North Bihar Electricity', code: 'NBE', serviceType: 'Electricity' },
  { name: 'JBVNL - JHARKHAND', code: 'JBVNL', serviceType: 'Electricity' },
  { name: 'Assam Power Distribution Company Ltd (RAPDR)', code: 'APDCLR', serviceType: 'Electricity' },
  { name: 'Mangalore Electricity Supply Co. Ltd (MESCOM) - RAPDR', code: 'MESCOMR', serviceType: 'Electricity' },
  { name: 'APDCL (Non-RAPDR) - ASSAM', code: 'APDCLN', serviceType: 'Electricity' },
  { name: 'Mangalore Electricity Supply Co. Ltd (Non) - RAPDR', code: 'MESCOMNR', serviceType: 'Electricity' },
  { name: 'BSES Rajdhani Power Limited - Delhi', code: 'BSES', serviceType: 'Electricity' },
  { name: 'BSES Yamuna Power Limited - Delhi', code: 'BSESY', serviceType: 'Electricity' },
  { name: 'Tata Power Delhi Limited - Delhi', code: 'TPD', serviceType: 'Electricity' },
  { name: 'Tata Power - MUMBAI', code: 'TPDM', serviceType: 'Electricity' },
  { name: 'Hubli Electricity Supply Company Ltd. (HESCOM)', code: 'HESCOM', serviceType: 'Electricity' },
  { name: 'South Bihar Electricity', code: 'SBE', serviceType: 'Electricity' },
  { name: 'BEST Mumbai', code: 'BEST', serviceType: 'Electricity' },
  { name: 'Ajmer Vidyut Vitran Nigam - RAJASTHAN', code: 'AJV', serviceType: 'Electricity' },
  { name: 'Bangalore ElectricitySupply Company', code: 'BESCOM', serviceType: 'Electricity' },
  { name: 'CESC - WEST BENGAL', code: 'CESC', serviceType: 'Electricity' },
  { name: 'Jaipur Vidyut Vitran Nigam - RAJASTHAN', code: 'JVV', serviceType: 'Electricity' },
  { name: 'Jodhpur Vidyut Vitran Nigam - RAJASTHAN', code: 'JDVV', serviceType: 'Electricity' },
  { name: 'MP Madhaya Kshetra Vidyut Vitaran -Urban', code: 'MKV', serviceType: 'Electricity' },
  { name: 'MSEDC - MAHARASHTRA', code: 'MSEDC', serviceType: 'Electricity' },
  { name: 'Noida Power - NOIDA', code: 'NP', serviceType: 'Electricity' },
  { name: 'Paschim Kshetra Vitaran - MADHYA PRADESH', code: 'PKV', serviceType: 'Electricity' },
  { name: 'Southern Power - ANDHRA PRADESH', code: 'SPA', serviceType: 'Electricity' },
  { name: 'Southern Power - TELANGANA', code: 'SPT', serviceType: 'Electricity' },
  { name: 'Torrent Power agra', code: 'TRP', serviceType: 'Electricity' },
  { name: 'Central Power Distribution Company of Andhra Pradesh Ltd', code: 'APCPDCL', serviceType: 'Electricity' },
  { name: 'Department of Power Arunachal Pradesh', code: 'ARPDOP', serviceType: 'Electricity' },
  { name: 'Western Electricity supply co. Of orissa ltd.', code: 'WESCO', serviceType: 'Electricity' },
  { name: 'Paschim Gujarat Vij Company Ltd', code: 'PGVCL', serviceType: 'Electricity' },
  { name: 'BharatpurElectricityServicesLtd', code: 'BHES', serviceType: 'Electricity' },
  { name: 'Muzaffarpur Vidyut Vitran', code: 'MVV', serviceType: 'Electricity' },
  { name: 'Madhya Gujarat Vij Company Ltd', code: 'MGVCL', serviceType: 'Electricity' },
  { name: 'MEPDCL - MEGHALAYA', code: 'MEPDCL', serviceType: 'Electricity' },
  { name: 'KEDL - KOTA', code: 'KEDL', serviceType: 'Electricity' },
  { name: 'Dakshin Gujarat Vij Company Ltd', code: 'DGVCL', serviceType: 'Electricity' },
  { name: 'WBSEDCL - WEST BENGAL', code: 'WBSEDCL', serviceType: 'Electricity' },
  { name: 'SNDL Power - NAGPUR', code: 'SNDL', serviceType: 'Electricity' },
  { name: 'Bikaner Electricity Supply Limited', code: 'BESL', serviceType: 'Electricity' },
  { name: 'India Power - WEST BENGAL', code: 'IPWB', serviceType: 'Electricity' },
  { name: 'BrihanMumbaiElectricSupplyandTransportUndertaking', code: 'BMESTU', serviceType: 'Electricity' },
  { name: 'APEPDCL - ANDHRA PRADESH', code: 'APEPDCL', serviceType: 'Electricity' },
  { name: 'TNEB - TAMIL NADU', code: 'TNEB', serviceType: 'Electricity' },
  { name: 'UPPCL (URBAN) - UTTAR PRADESH', code: 'UPPCLU', serviceType: 'Electricity' },
  { name: 'Uttar Pradesh Power Corporation Limited(Rular)', code: 'UPPCLR', serviceType: 'Electricity' },
  { name: 'DakshinHaryanaBijliVitranNigam', code: 'DHBVN', serviceType: 'Electricity' },
  { name: 'TSNPDCL Telangana northern power', code: 'TSNPDCL', serviceType: 'Electricity' },
  { name: 'DNHPowerDistributionCompanyLimited', code: 'DDCL', serviceType: 'Electricity' },
  { name: 'GulbargaElectricitySupplyCompanyLimited', code: 'GESCL', serviceType: 'Electricity' },
  { name: 'IndiaPowerCorporationLimited', code: 'IPCL', serviceType: 'Electricity' },
  { name: 'JamshedpurUtilitiesandServicesCompanyLimited', code: 'JUSCL', serviceType: 'Electricity' },
  { name: 'Chhattisgarh State Power Distribution Company Ltd. (CSPDCL)', code: 'CSPDCL', serviceType: 'Electricity' },
  { name: 'Goa Electricity', code: 'GOAELC', serviceType: 'Electricity' },
  { name: 'UttarGujarat Vij Company Ltd', code: 'UGVCL', serviceType: 'Electricity' },
  { name: 'Torrent Power Surat', code: 'TORRENTSUR', serviceType: 'Electricity' },
  { name: 'Torrent Power Ahemdabad', code: 'TORRENTAHM', serviceType: 'Electricity' },
  { name: 'Gift Power Company Limited', code: 'GPCL', serviceType: 'Electricity' },
  { name: 'Himachal Pradesh State Electricity Board Ltd', code: 'HPSEBL', serviceType: 'Electricity' },
  { name: 'Jammu & Kashmir power Development department', code: 'JKPDD', serviceType: 'Electricity' },
  { name: 'Chamundeshwari Electricity Supply Corporation Ltd. (Cesc,Mysore)', code: 'CESCOM', serviceType: 'Electricity' },
  { name: 'NorthDelhiPowerLimited', code: 'NDPL', serviceType: 'Electricity' },
  { name: 'MUNICIPALCORPORATIONOFGURUGRAM', code: 'MCG', serviceType: 'Electricity' },
  { name: 'Punjab State Power Corporation Limted', code: 'PSPCL', serviceType: 'Electricity' },
  { name: 'TripuraStateElectricityCorporationLtd', code: 'TSECL', serviceType: 'Electricity' },
  { name: 'UttarHaryanaBijliVitranNigam', code: 'UHBV', serviceType: 'Electricity' },
  { name: 'UttarakhandPowerCorporationLimited', code: 'UKPCL', serviceType: 'Electricity' },
  { name: 'Kerala State Electricity Board Ltd.', code: 'KSEB', serviceType: 'Electricity' },
  { name: 'kannan devan hills power', code: 'KDHPCPL', serviceType: 'Electricity' },
  { name: 'Lakshadweep Electricity Department', code: 'LED', serviceType: 'Electricity' },
  { name: 'MP Poorv Kshetra Vidyut Vitaran - Jabalpur', code: 'MPPKVVCLPU', serviceType: 'Electricity' },
  { name: 'MP Poorv Kshetra Vidyut Vitaran - Rular', code: 'MPPKVVCLPU', serviceType: 'Electricity' },
  { name: 'Madhya Pradesh Madhya Kshetra Vidyut Vitaran-RURAL', code: 'MPPKVVCLMR', serviceType: 'Electricity' },
  { name: 'Madhya Pradesh Poorv Kshetra Vidyut Vitaran-URBAN', code: 'MPPKVVCL', serviceType: 'Electricity' },
  { name: 'Reliance Energy', code: 'RELIANCE', serviceType: 'Electricity' },
  { name: 'Torrent Power SHIL', code: 'TORRENTSHI', serviceType: 'Electricity' },
  { name: 'Torrent Power Bhivandi', code: 'TORRENTBHI', serviceType: 'Electricity' },
  { name: 'Adani power', code: 'AEML', serviceType: 'Electricity' },
  { name: 'Manipur State Power Distribution Company Limited (Prepaid)', code: 'MSPDCLPR', serviceType: 'Electricity' },
  { name: 'Power & Electricity Department - Mizoram', code: 'MPED', serviceType: 'Electricity' },
  { name: 'Department of Power, Nagaland', code: 'NDOP', serviceType: 'Electricity' },
  { name: 'New Delhi Municipal Council (NDMC) - Electricity', code: 'NDMC', serviceType: 'Electricity' },
  { name: 'NESCO Odisha', code: 'NESCO', serviceType: 'Electricity' },
  { name: 'SOUTHCO Odisha', code: 'SOUTHCO', serviceType: 'Electricity' },
  { name: 'TP central odisha distribution limited', code: 'TPCODL', serviceType: 'Electricity' },
  { name: 'Government of Puducherry Electricity Department', code: 'PGPED', serviceType: 'Electricity' },
  { name: 'TP Ajmer Distribution Ltd', code: 'TPADL', serviceType: 'Electricity' },
  { name: 'Sikkim Power Rural', code: 'SPR', serviceType: 'Electricity' },
  { name: 'Sikkim Power Urban', code: 'SPU', serviceType: 'Electricity' },
  { name: 'Kanpur Electricity Supply Company', code: 'KESCO', serviceType: 'Electricity' },
  { name: 'Torrent Power Dahej', code: 'TORRENTDAH', serviceType: 'Electricity' },
  { name: 'Madhyanchal Vidyut Vitran Nigam Limited', code: 'MVVNL', serviceType: 'Electricity' },
  { name: 'Mahanagar Gas', code: 'MG', serviceType: 'Gas' },
  { name: 'Adani Gas', code: 'AG', serviceType: 'Gas' },
  { name: 'Gujarat Gas', code: 'GG', serviceType: 'Gas' },
  { name: 'Indraprastha Gas', code: 'IG', serviceType: 'Gas' },
  { name: 'Hindustan Petroleum Corporation Ltd', code: 'HPCLGC', serviceType: 'Gas' },
  { name: 'ICICI Prudential Insurance', code: 'ICP', serviceType: 'Insurance' },
  { name: 'Tata AIA Insurance', code: 'TAI', serviceType: 'Insurance' },
  { name: 'IMPS', code: 'IMPS', serviceType: 'Money Transfer' },
  { name: 'Reliance NetConnect 1X', code: 'RNET', serviceType: 'Data Card' },
  { name: 'Reliance NetConnect 3G', code: 'RNET3', serviceType: 'Data Card' },
  { name: 'Reliance NetConnect+', code: 'RNETP', serviceType: 'Data Card' },
  { name: 'Tata Photon Whiz', code: 'TPW', serviceType: 'Data Card' },
  { name: 'Tata Photon+', code: 'TPP', serviceType: 'Data Card' },
  { name: 'MTS Mblaze', code: 'MTM', serviceType: 'Data Card' },
  { name: 'MTS Mbrowse', code: 'MTBR', serviceType: 'Data Card' },
  { name: 'Paul Merchants', code: 'PMF', serviceType: 'Other' },
  { name: 'Jammu And Kashmir Bank Fastag', code: 'JKF', serviceType: 'Fastag' },
  { name: 'Kotak Mahindra Bank - Fastag', code: 'KMF', serviceType: 'Fastag' },
  { name: 'Indusind Bank Fastag', code: 'INDF', serviceType: 'Fastag' },
  { name: 'Indian Highways Management Company Ltd Fastag', code: 'IHMCF', serviceType: 'Fastag' },
  { name: 'Idfc First Bank- Fastag', code: 'IFF', serviceType: 'Fastag' },
  { name: 'Icici Bank Fastag', code: 'ICF', serviceType: 'Fastag' },
  { name: 'Hdfc Bank - Fastag', code: 'HDF', serviceType: 'Fastag' },
  { name: 'Equitas Fastag Recharge', code: 'EFF', serviceType: 'Fastag' },
  { name: 'Bank Of Baroda - Fastag', code: 'BBF', serviceType: 'Fastag' },
  { name: 'Axis Bank Fastag', code: 'AXF', serviceType: 'Fastag' },
  { name: 'Federal Bank - Fastag', code: 'FDF', serviceType: 'Fastag' },
  { name: 'Paytm Payments Bank Fastag', code: 'PTF', serviceType: 'Fastag' },
  { name: 'Airtel Payments Bank', code: 'APB', serviceType: 'Fastag' },
  { name: 'Idbi Bank Fastag', code: 'IBF', serviceType: 'Fastag' },
  { name: 'Sbi Bank Fastag', code: 'SBF', serviceType: 'Fastag' },
  { name: 'Google Play', code: 'GLF', serviceType: 'Other' },
  { name: 'NSDL EKYC PAN (Instant Pan)', code: 'EKYC', serviceType: 'Other' },
  { name: 'NSDL ESIGN PAN (Scan Based with photo and signature)', code: 'ESIGN', serviceType: 'Other' },
  { name: 'NSDL EKYC PAN CORRECTION (Instant Pan)', code: 'CEKYC', serviceType: 'Other' },
  { name: 'NSDL ESIGN PAN CORRECTION (Scan Based with photo and signature)', code: 'CESIGN', serviceType: 'Other' },
  { name: 'BSNL Recharge', code: 'BS', serviceType: 'Other' },
  { name: 'MTNL - Recharge', code: 'MTR', serviceType: 'Other' },
  { name: 'MTNL – TOPUP', code: 'MTT', serviceType: 'Other' },
  { name: 'Idea Lapu', code: 'RI', serviceType: 'Other' }
];

const seedOperators = async () => {
  try {
    await connectDB();
    console.log('Seeding Operators...');

    let displayOrder = 1;
    for (const op of operators) {
      await ProviderOperator.findOneAndUpdate(
        { provider: 'A1Topup', code: op.code },
        { 
          provider: 'A1Topup',
          name: op.name,
          code: op.code,
          serviceType: op.serviceType,
          displayOrder: displayOrder++
        },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }
    
    console.log(`Successfully seeded ${operators.length} operators.`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding operators:', error);
    process.exit(1);
  }
};

seedOperators();
