// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2864fb41zrxok7viXcBX9xOIVWPqvUtA',
    appId: '1:765569713221:web:83821fe5d8949e7bc30f2c',
    messagingSenderId: '765569713221',
    projectId: 'shopulse-a954e',
    authDomain: 'shopulse-a954e.firebaseapp.com',
    storageBucket: 'shopulse-a954e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFby7MFkFfMzZMFCTna1v_kvdAm57KM0',
    appId: '1:765569713221:android:3eaedadd9e6d1e13c30f2c',
    messagingSenderId: '765569713221',
    projectId: 'shopulse-a954e',
    storageBucket: 'shopulse-a954e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQnPDORHSSC0ahpOWs3suIe7WqoOmW6po',
    appId: '1:765569713221:ios:2085548f92b7c72bc30f2c',
    messagingSenderId: '765569713221',
    projectId: 'shopulse-a954e',
    storageBucket: 'shopulse-a954e.firebasestorage.app',
    iosBundleId: 'com.a1recharge.a1Recharge',
  );
}
